// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'sqlite_model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Task.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Task TABLE
class TableTask extends SqfEntityTableBase {
  TableTask() {
    // declare properties of EntityTable
    tableName = 'tasks';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('title', DbType.text, isNotNull: false),
      SqfEntityFieldBase('description', DbType.text, isNotNull: false),
      SqfEntityFieldBase('date', DbType.date,
          isNotNull: false, minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('time_do_at', DbType.datetime,
          isNotNull: false, minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('is_done', DbType.bool,
          defaultValue: false, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableTask();
  }
}

// Taskchecklist TABLE
class TableTaskchecklist extends SqfEntityTableBase {
  TableTaskchecklist() {
    // declare properties of EntityTable
    tableName = 'taskchecklists';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('name', DbType.text, isNotNull: false),
      SqfEntityFieldRelationshipBase(TableTask.getInstance, DeleteRule.CASCADE,
          relationType: RelationType.ONE_TO_MANY,
          fieldName: 'tasksId',
          defaultValue: 0,
          isNotNull: false),
      SqfEntityFieldBase('is_done', DbType.bool,
          defaultValue: false, isNotNull: false),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableTaskchecklist();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class PotomoDB extends SqfEntityModelProvider {
  PotomoDB() {
    databaseName = potomoDB.databaseName;
    password = potomoDB.password;
    dbVersion = potomoDB.dbVersion;
    databaseTables = [
      TableTask.getInstance,
      TableTaskchecklist.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = potomoDB
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Task
class Task {
  Task(
      {this.id,
      this.title,
      this.description,
      this.date,
      this.time_do_at,
      this.is_done}) {
    _setDefaultValues();
  }
  Task.withFields(
      this.title, this.description, this.date, this.time_do_at, this.is_done) {
    _setDefaultValues();
  }
  Task.withId(this.id, this.title, this.description, this.date, this.time_do_at,
      this.is_done) {
    _setDefaultValues();
  }
  Task.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['title'] != null) {
      title = o['title'] as String;
    }
    if (o['description'] != null) {
      description = o['description'] as String;
    }
    if (o['date'] != null) {
      date = int.tryParse(o['date'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['date'].toString()))
          : DateTime.tryParse(o['date'].toString());
    }
    if (o['time_do_at'] != null) {
      time_do_at = int.tryParse(o['time_do_at'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['time_do_at'].toString()))
          : DateTime.tryParse(o['time_do_at'].toString());
    }
    if (o['is_done'] != null) {
      is_done = o['is_done'] == 1 || o['is_done'] == true;
    }
  }
  // FIELDS (Task)
  int id;
  String title;
  String description;
  DateTime date;
  DateTime time_do_at;
  bool is_done;

  BoolResult saveResult;
  // end FIELDS (Task)

// COLLECTIONS & VIRTUALS (Task)
  /// to load children of items to this field, use preload parameter. Ex: toList(preload:true) or toSingle(preload:true) or getById(preload:true)
  /// You can also specify this object into certain preload fields. Ex: toList(preload:true, preloadFields:['plTaskchecklists', 'plField2'..]) or so on..
  List<Taskchecklist> plTaskchecklists;

  /// get Taskchecklist(s) filtered by id=tasksId
  TaskchecklistFilterBuilder getTaskchecklists(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    if (id == null) {
      return null;
    }
    return Taskchecklist()
        .select(columnsToSelect: columnsToSelect, getIsDeleted: getIsDeleted)
        .tasksId
        .equals(id)
        .and;
  }

// END COLLECTIONS & VIRTUALS (Task)

  static const bool _softDeleteActivated = false;
  TaskManager __mnTask;

  TaskManager get _mnTask {
    return __mnTask = __mnTask ?? TaskManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (description != null) {
      map['description'] = description;
    }

    if (date != null) {
      map['date'] = forJson
          ? '$date.year-$date.month-$date.day'
          : forQuery
              ? DateTime(date.year, date.month, date.day).millisecondsSinceEpoch
              : date;
    }

    if (time_do_at != null) {
      map['time_do_at'] = forJson
          ? time_do_at.toString()
          : forQuery ? time_do_at.millisecondsSinceEpoch : time_do_at;
    }

    if (is_done != null) {
      map['is_done'] = forQuery ? (is_done ? 1 : 0) : is_done;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (description != null) {
      map['description'] = description;
    }

    if (date != null) {
      map['date'] = forJson
          ? '$date.year-$date.month-$date.day'
          : forQuery
              ? DateTime(date.year, date.month, date.day).millisecondsSinceEpoch
              : date;
    }

    if (time_do_at != null) {
      map['time_do_at'] = forJson
          ? time_do_at.toString()
          : forQuery ? time_do_at.millisecondsSinceEpoch : time_do_at;
    }

    if (is_done != null) {
      map['is_done'] = forQuery ? (is_done ? 1 : 0) : is_done;
    }

// COLLECTIONS (Task)
    if (!forQuery) {
      map['Taskchecklists'] = await getTaskchecklists().toMapList();
    }
// END COLLECTIONS (Task)

    return map;
  }

  /// This method returns Json String [Task]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Task]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      title,
      description,
      date != null ? date.millisecondsSinceEpoch : null,
      time_do_at != null ? time_do_at.millisecondsSinceEpoch : null,
      is_done
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      title,
      description,
      date != null ? date.millisecondsSinceEpoch : null,
      time_do_at != null ? time_do_at.millisecondsSinceEpoch : null,
      is_done
    ];
  }

  static Future<List<Task>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Task.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Task>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Task>[];
    try {
      objList = list
          .map((task) => Task.fromMap(task as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Task.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Task>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Task> objList = <Task>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Task.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);
      // final List<String> _loadedFields = List<String>.from(loadedFields);

      // RELATIONSHIPS PRELOAD CHILD
      if (preload) {
        loadedFields = loadedFields ?? [];
        if (/*!_loadedFields.contains('tasks.plTaskchecklists') && */ (preloadFields ==
                null ||
            preloadFields.contains('plTaskchecklists'))) {
          /*_loadedFields.add('tasks.plTaskchecklists'); */
          obj.plTaskchecklists = obj.plTaskchecklists ??
              await obj.getTaskchecklists().toList(
                  preload: preload,
                  preloadFields: preloadFields,
                  loadParents: false /*, loadedFields:_loadedFields*/);
        }
      } // END RELATIONSHIPS PRELOAD CHILD

      objList.add(obj);
    }
    return objList;
  }

  /// returns Task by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Task if exist, otherwise returns null
  Future<Task> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Task obj;
    final data = await _mnTask.getById([id]);
    if (data.length != 0) {
      obj = Task.fromMap(data[0] as Map<String, dynamic>);
      // final List<String> _loadedFields = loadedFields ?? [];

      // RELATIONSHIPS PRELOAD CHILD
      if (preload) {
        loadedFields = loadedFields ?? [];
        if (/*!_loadedFields.contains('tasks.plTaskchecklists') && */ (preloadFields ==
                null ||
            preloadFields.contains('plTaskchecklists'))) {
          /*_loadedFields.add('tasks.plTaskchecklists'); */
          obj.plTaskchecklists = obj.plTaskchecklists ??
              await obj.getTaskchecklists().toList(
                  preload: preload,
                  preloadFields: preloadFields,
                  loadParents: false /*, loadedFields:_loadedFields*/);
        }
      } // END RELATIONSHIPS PRELOAD CHILD

    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Task) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnTask.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnTask.update(this);
    }

    return id;
  }

  /// saveAs Task. Returns a new Primary Key value of Task

  /// <returns>Returns a new Primary Key value of Task
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Task> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Task> tasks) async {
    // final results = _mnTask.saveAll('INSERT OR REPLACE INTO tasks (id,title, description, date, time_do_at, is_done)  VALUES (?,?,?,?,?,?)',tasks);
    // return results; removed in sqfentity_gen 1.3.0+6
    await PotomoDB().batchStart();
    for (final obj in tasks) {
      await obj.save();
    }
    //    return PotomoDB().batchCommit();
    final result = await PotomoDB().batchCommit();
    for (int i = 0; i < tasks.length; i++) {
      if (tasks[i].id == null) {
        tasks[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnTask.rawInsert(
              'INSERT OR REPLACE INTO tasks (id,title, description, date, time_do_at, is_done)  VALUES (?,?,?,?,?,?)',
              [
                id,
                title,
                description,
                date != null ? date.millisecondsSinceEpoch : null,
                time_do_at != null ? time_do_at.millisecondsSinceEpoch : null,
                is_done
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true, successMessage: 'Task id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Task id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Task Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Task>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Task> tasks) async {
    final results = await _mnTask.rawInsertAll(
        'INSERT OR REPLACE INTO tasks (id,title, description, date, time_do_at, is_done)  VALUES (?,?,?,?,?,?)',
        tasks);
    return results;
  }

  /// Deletes Task

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Task invoked (id=$id)');
    var result = BoolResult();
    {
      result = await Taskchecklist()
          .select()
          .tasksId
          .equals(id)
          .and
          .delete(hardDelete);
    }
    if (!result.success) {
      return result;
    }
    if (!_softDeleteActivated || hardDelete) {
      return _mnTask
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnTask.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  TaskFilterBuilder select({List<String> columnsToSelect, bool getIsDeleted}) {
    return TaskFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  TaskFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return TaskFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    is_done = is_done ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion task

// region TaskField
class TaskField extends SearchCriteria {
  TaskField(this.taskFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  TaskFilterBuilder taskFB;

  TaskField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  TaskFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    taskFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskFB.parameters, param, SqlSyntax.EQuals,
            taskFB._addedBlocks)
        : setCriteria(pValue, taskFB.parameters, param, SqlSyntax.NotEQuals,
            taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    taskFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskFB.parameters, param, SqlSyntax.EQualsOrNull,
            taskFB._addedBlocks)
        : setCriteria(pValue, taskFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder isNull() {
    taskFB._addedBlocks = setCriteria(
        0,
        taskFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      taskFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          taskFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskFB._addedBlocks);
      _waitingNot = '';
      taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
          taskFB._addedBlocks.retVal;
    }
    return taskFB;
  }

  TaskFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      taskFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          taskFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskFB._addedBlocks);
      _waitingNot = '';
      taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
          taskFB._addedBlocks.retVal;
      taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
          taskFB._addedBlocks.retVal;
    }
    return taskFB;
  }

  TaskFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      taskFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          taskFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskFB._addedBlocks);
      _waitingNot = '';
      taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
          taskFB._addedBlocks.retVal;
    }
    return taskFB;
  }

  TaskFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      taskFB._addedBlocks = setCriteria(
          pFirst,
          taskFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        taskFB._addedBlocks = setCriteria(pFirst, taskFB.parameters, param,
            SqlSyntax.LessThan, taskFB._addedBlocks);
      } else {
        taskFB._addedBlocks = setCriteria(pFirst, taskFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, taskFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        taskFB._addedBlocks = setCriteria(pLast, taskFB.parameters, param,
            SqlSyntax.GreaterThan, taskFB._addedBlocks);
      } else {
        taskFB._addedBlocks = setCriteria(pLast, taskFB.parameters, param,
            SqlSyntax.LessThanOrEquals, taskFB._addedBlocks);
      }
    }
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    taskFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskFB.parameters, param, SqlSyntax.GreaterThan,
            taskFB._addedBlocks)
        : setCriteria(pValue, taskFB.parameters, param,
            SqlSyntax.LessThanOrEquals, taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    taskFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskFB.parameters, param, SqlSyntax.LessThan,
            taskFB._addedBlocks)
        : setCriteria(pValue, taskFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    taskFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, taskFB._addedBlocks)
        : setCriteria(pValue, taskFB.parameters, param, SqlSyntax.LessThan,
            taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    taskFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskFB.parameters, param,
            SqlSyntax.LessThanOrEquals, taskFB._addedBlocks)
        : setCriteria(pValue, taskFB.parameters, param, SqlSyntax.GreaterThan,
            taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }

  TaskFilterBuilder inValues(dynamic pValue) {
    taskFB._addedBlocks = setCriteria(
        pValue,
        taskFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        taskFB._addedBlocks);
    _waitingNot = '';
    taskFB._addedBlocks.needEndBlock[taskFB._blockIndex] =
        taskFB._addedBlocks.retVal;
    return taskFB;
  }
}
// endregion TaskField

// region TaskFilterBuilder
class TaskFilterBuilder extends SearchCriteria {
  TaskFilterBuilder(Task obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Task _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  TaskFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  TaskFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  TaskFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  TaskFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  TaskFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  TaskFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  TaskFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  TaskFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  TaskFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  TaskFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  TaskFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  TaskField setField(TaskField field, String colName, DbType dbtype) {
    return TaskField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  TaskField _id;
  TaskField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  TaskField _title;
  TaskField get title {
    return _title = setField(_title, 'title', DbType.text);
  }

  TaskField _description;
  TaskField get description {
    return _description = setField(_description, 'description', DbType.text);
  }

  TaskField _date;
  TaskField get date {
    return _date = setField(_date, 'date', DbType.date);
  }

  TaskField _time_do_at;
  TaskField get time_do_at {
    return _time_do_at = setField(_time_do_at, 'time_do_at', DbType.datetime);
  }

  TaskField _is_done;
  TaskField get is_done {
    return _is_done = setField(_is_done, 'is_done', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Task._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Task> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();
    // Delete sub records where in (Taskchecklist) according to DeleteRule.CASCADE
    final idListTaskchecklistBYtasksId = toListPrimaryKeySQL(false);
    final resTaskchecklistBYtasksId = await Taskchecklist()
        .select()
        .where('tasksId IN (${idListTaskchecklistBYtasksId['sql']})',
            parameterValue: idListTaskchecklistBYtasksId['args'])
        .delete(hardDelete);
    if (!resTaskchecklistBYtasksId.success) {
      return resTaskchecklistBYtasksId;
    }

    if (Task._softDeleteActivated && !hardDelete) {
      r = await _obj._mnTask.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnTask.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from tasks ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnTask.updateBatch(qparams, values);
  }

  /// This method always returns Task Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Task>
  Future<Task> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnTask.toList(qparams);
    final data = await objFuture;
    Task obj;
    if (data.isNotEmpty) {
      obj = Task.fromMap(data[0] as Map<String, dynamic>);
      // final List<String> _loadedFields = loadedFields ?? [];

      // RELATIONSHIPS PRELOAD CHILD
      if (preload) {
        loadedFields = loadedFields ?? [];
        if (/*!_loadedFields.contains('tasks.plTaskchecklists') && */ (preloadFields ==
                null ||
            preloadFields.contains('plTaskchecklists'))) {
          /*_loadedFields.add('tasks.plTaskchecklists'); */
          obj.plTaskchecklists = obj.plTaskchecklists ??
              await obj.getTaskchecklists().toList(
                  preload: preload,
                  preloadFields: preloadFields,
                  loadParents: false /*, loadedFields:_loadedFields*/);
        }
      } // END RELATIONSHIPS PRELOAD CHILD

    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Task]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) taskCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final tasksFuture = await _obj._mnTask.toList(qparams);
    final int count = tasksFuture[0]['CNT'] as int;
    if (taskCount != null) {
      taskCount(count);
    }
    return count;
  }

  /// This method returns List<Task> [Task]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Task>
  Future<List<Task>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Task> tasksData = await Task.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return tasksData;
  }

  /// This method returns Json String [Task]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Task]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Task]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnTask.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Task]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM tasks WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnTask.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Task]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnTask.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Task.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnTask.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion TaskFilterBuilder

// region TaskFields
class TaskFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField _fDescription;
  static TableField get description {
    return _fDescription = _fDescription ??
        SqlSyntax.setField(_fDescription, 'description', DbType.text);
  }

  static TableField _fDate;
  static TableField get date {
    return _fDate = _fDate ?? SqlSyntax.setField(_fDate, 'date', DbType.date);
  }

  static TableField _fTime_do_at;
  static TableField get time_do_at {
    return _fTime_do_at = _fTime_do_at ??
        SqlSyntax.setField(_fTime_do_at, 'time_do_at', DbType.datetime);
  }

  static TableField _fIs_done;
  static TableField get is_done {
    return _fIs_done =
        _fIs_done ?? SqlSyntax.setField(_fIs_done, 'is_done', DbType.bool);
  }
}
// endregion TaskFields

//region TaskManager
class TaskManager extends SqfEntityProvider {
  TaskManager()
      : super(PotomoDB(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'tasks';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion TaskManager
// region Taskchecklist
class Taskchecklist {
  Taskchecklist({this.id, this.name, this.tasksId, this.is_done}) {
    _setDefaultValues();
  }
  Taskchecklist.withFields(this.name, this.tasksId, this.is_done) {
    _setDefaultValues();
  }
  Taskchecklist.withId(this.id, this.name, this.tasksId, this.is_done) {
    _setDefaultValues();
  }
  Taskchecklist.fromMap(Map<String, dynamic> o,
      {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['name'] != null) {
      name = o['name'] as String;
    }
    tasksId = int.tryParse(o['tasksId'].toString());

    if (o['is_done'] != null) {
      is_done = o['is_done'] == 1 || o['is_done'] == true;
    }

    // RELATIONSHIPS FromMAP
    plTask = o['task'] != null
        ? Task.fromMap(o['task'] as Map<String, dynamic>)
        : null;
    // END RELATIONSHIPS FromMAP
  }
  // FIELDS (Taskchecklist)
  int id;
  String name;
  int tasksId;
  bool is_done;

  BoolResult saveResult;
  // end FIELDS (Taskchecklist)

// RELATIONSHIPS (Taskchecklist)
  /// to load parent of items to this field, use preload parameter ex: toList(preload:true) or toSingle(preload:true) or getById(preload:true)
  /// You can also specify this object into certain preload fields. Ex: toList(preload:true, preloadFields:['plTask', 'plField2'..]) or so on..
  Task plTask;

  /// get Task By TasksId
  Future<Task> getTask(
      {bool loadParents = false, List<String> loadedFields}) async {
    final _obj = await Task()
        .getById(tasksId, loadParents: loadParents, loadedFields: loadedFields);
    return _obj;
  }
  // END RELATIONSHIPS (Taskchecklist)

  static const bool _softDeleteActivated = false;
  TaskchecklistManager __mnTaskchecklist;

  TaskchecklistManager get _mnTaskchecklist {
    return __mnTaskchecklist = __mnTaskchecklist ?? TaskchecklistManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    if (tasksId != null) {
      map['tasksId'] = forView ? plTask.title : tasksId;
    }

    if (is_done != null) {
      map['is_done'] = forQuery ? (is_done ? 1 : 0) : is_done;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (name != null) {
      map['name'] = name;
    }

    if (tasksId != null) {
      map['tasksId'] = forView ? plTask.title : tasksId;
    }

    if (is_done != null) {
      map['is_done'] = forQuery ? (is_done ? 1 : 0) : is_done;
    }

    return map;
  }

  /// This method returns Json String [Taskchecklist]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Taskchecklist]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [name, tasksId, is_done];
  }

  List<dynamic> toArgsWithIds() {
    return [id, name, tasksId, is_done];
  }

  static Future<List<Taskchecklist>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Taskchecklist.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Taskchecklist>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Taskchecklist>[];
    try {
      objList = list
          .map((taskchecklist) =>
              Taskchecklist.fromMap(taskchecklist as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print(
          'SQFENTITY ERROR Taskchecklist.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Taskchecklist>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Taskchecklist> objList = <Taskchecklist>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Taskchecklist.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);
      // final List<String> _loadedFields = List<String>.from(loadedFields);

      // RELATIONSHIPS PRELOAD
      if (preload || loadParents) {
        loadedFields = loadedFields ?? [];
        if (/*!_loadedFields.contains('tasks.plTask') && */ (preloadFields ==
                null ||
            loadParents ||
            preloadFields.contains('plTask'))) {
          /*_loadedFields.add('tasks.plTask');*/
          obj.plTask = obj.plTask ??
              await obj.getTask(
                  loadParents: loadParents /*, loadedFields: _loadedFields*/);
        }
      } // END RELATIONSHIPS PRELOAD

      objList.add(obj);
    }
    return objList;
  }

  /// returns Taskchecklist by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Taskchecklist if exist, otherwise returns null
  Future<Taskchecklist> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Taskchecklist obj;
    final data = await _mnTaskchecklist.getById([id]);
    if (data.length != 0) {
      obj = Taskchecklist.fromMap(data[0] as Map<String, dynamic>);
      // final List<String> _loadedFields = loadedFields ?? [];

      // RELATIONSHIPS PRELOAD
      if (preload || loadParents) {
        loadedFields = loadedFields ?? [];
        if (/*!_loadedFields.contains('tasks.plTask') && */ (preloadFields ==
                null ||
            loadParents ||
            preloadFields.contains('plTask'))) {
          /*_loadedFields.add('tasks.plTask');*/
          obj.plTask = obj.plTask ??
              await obj.getTask(
                  loadParents: loadParents /*, loadedFields: _loadedFields*/);
        }
      } // END RELATIONSHIPS PRELOAD

    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Taskchecklist) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnTaskchecklist.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnTaskchecklist.update(this);
    }

    return id;
  }

  /// saveAs Taskchecklist. Returns a new Primary Key value of Taskchecklist

  /// <returns>Returns a new Primary Key value of Taskchecklist
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Taskchecklist> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(
      List<Taskchecklist> taskchecklists) async {
    // final results = _mnTaskchecklist.saveAll('INSERT OR REPLACE INTO taskchecklists (id,name, tasksId, is_done)  VALUES (?,?,?,?)',taskchecklists);
    // return results; removed in sqfentity_gen 1.3.0+6
    await PotomoDB().batchStart();
    for (final obj in taskchecklists) {
      await obj.save();
    }
    //    return PotomoDB().batchCommit();
    final result = await PotomoDB().batchCommit();
    for (int i = 0; i < taskchecklists.length; i++) {
      if (taskchecklists[i].id == null) {
        taskchecklists[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnTaskchecklist.rawInsert(
              'INSERT OR REPLACE INTO taskchecklists (id,name, tasksId, is_done)  VALUES (?,?,?,?)',
              [id, name, tasksId, is_done]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Taskchecklist id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false,
            errorMessage: 'Taskchecklist id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Taskchecklist Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Taskchecklist>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Taskchecklist> taskchecklists) async {
    final results = await _mnTaskchecklist.rawInsertAll(
        'INSERT OR REPLACE INTO taskchecklists (id,name, tasksId, is_done)  VALUES (?,?,?,?)',
        taskchecklists);
    return results;
  }

  /// Deletes Taskchecklist

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Taskchecklist invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnTaskchecklist
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnTaskchecklist.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  TaskchecklistFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return TaskchecklistFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  TaskchecklistFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return TaskchecklistFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    tasksId = tasksId ?? 0;
    is_done = is_done ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion taskchecklist

// region TaskchecklistField
class TaskchecklistField extends SearchCriteria {
  TaskchecklistField(this.taskchecklistFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  TaskchecklistFilterBuilder taskchecklistFB;

  TaskchecklistField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  TaskchecklistFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    taskchecklistFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.EQuals, taskchecklistFB._addedBlocks)
        : setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.NotEQuals, taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    taskchecklistFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.EQualsOrNull, taskchecklistFB._addedBlocks)
        : setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder isNull() {
    taskchecklistFB._addedBlocks = setCriteria(
        0,
        taskchecklistFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      taskchecklistFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          taskchecklistFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskchecklistFB._addedBlocks);
      _waitingNot = '';
      taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
          taskchecklistFB._addedBlocks.retVal;
    }
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      taskchecklistFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          taskchecklistFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskchecklistFB._addedBlocks);
      _waitingNot = '';
      taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
          taskchecklistFB._addedBlocks.retVal;
      taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
          taskchecklistFB._addedBlocks.retVal;
    }
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      taskchecklistFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          taskchecklistFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskchecklistFB._addedBlocks);
      _waitingNot = '';
      taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
          taskchecklistFB._addedBlocks.retVal;
    }
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      taskchecklistFB._addedBlocks = setCriteria(
          pFirst,
          taskchecklistFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          taskchecklistFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        taskchecklistFB._addedBlocks = setCriteria(
            pFirst,
            taskchecklistFB.parameters,
            param,
            SqlSyntax.LessThan,
            taskchecklistFB._addedBlocks);
      } else {
        taskchecklistFB._addedBlocks = setCriteria(
            pFirst,
            taskchecklistFB.parameters,
            param,
            SqlSyntax.GreaterThanOrEquals,
            taskchecklistFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        taskchecklistFB._addedBlocks = setCriteria(
            pLast,
            taskchecklistFB.parameters,
            param,
            SqlSyntax.GreaterThan,
            taskchecklistFB._addedBlocks);
      } else {
        taskchecklistFB._addedBlocks = setCriteria(
            pLast,
            taskchecklistFB.parameters,
            param,
            SqlSyntax.LessThanOrEquals,
            taskchecklistFB._addedBlocks);
      }
    }
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    taskchecklistFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.GreaterThan, taskchecklistFB._addedBlocks)
        : setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.LessThanOrEquals, taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    taskchecklistFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.LessThan, taskchecklistFB._addedBlocks)
        : setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    taskchecklistFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, taskchecklistFB._addedBlocks)
        : setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.LessThan, taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    taskchecklistFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.LessThanOrEquals, taskchecklistFB._addedBlocks)
        : setCriteria(pValue, taskchecklistFB.parameters, param,
            SqlSyntax.GreaterThan, taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }

  TaskchecklistFilterBuilder inValues(dynamic pValue) {
    taskchecklistFB._addedBlocks = setCriteria(
        pValue,
        taskchecklistFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        taskchecklistFB._addedBlocks);
    _waitingNot = '';
    taskchecklistFB._addedBlocks.needEndBlock[taskchecklistFB._blockIndex] =
        taskchecklistFB._addedBlocks.retVal;
    return taskchecklistFB;
  }
}
// endregion TaskchecklistField

// region TaskchecklistFilterBuilder
class TaskchecklistFilterBuilder extends SearchCriteria {
  TaskchecklistFilterBuilder(Taskchecklist obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Taskchecklist _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  TaskchecklistFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  TaskchecklistFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  TaskchecklistFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  TaskchecklistFilterBuilder where(String whereCriteria,
      {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  TaskchecklistFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  TaskchecklistFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  TaskchecklistFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  TaskchecklistFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  TaskchecklistFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  TaskchecklistFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  TaskchecklistFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  TaskchecklistField setField(
      TaskchecklistField field, String colName, DbType dbtype) {
    return TaskchecklistField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  TaskchecklistField _id;
  TaskchecklistField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  TaskchecklistField _name;
  TaskchecklistField get name {
    return _name = setField(_name, 'name', DbType.text);
  }

  TaskchecklistField _tasksId;
  TaskchecklistField get tasksId {
    return _tasksId = setField(_tasksId, 'tasksId', DbType.integer);
  }

  TaskchecklistField _is_done;
  TaskchecklistField get is_done {
    return _is_done = setField(_is_done, 'is_done', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Taskchecklist._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Taskchecklist> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Taskchecklist._softDeleteActivated && !hardDelete) {
      r = await _obj._mnTaskchecklist.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnTaskchecklist.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from taskchecklists ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnTaskchecklist.updateBatch(qparams, values);
  }

  /// This method always returns Taskchecklist Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Taskchecklist>
  Future<Taskchecklist> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnTaskchecklist.toList(qparams);
    final data = await objFuture;
    Taskchecklist obj;
    if (data.isNotEmpty) {
      obj = Taskchecklist.fromMap(data[0] as Map<String, dynamic>);
      // final List<String> _loadedFields = loadedFields ?? [];

      // RELATIONSHIPS PRELOAD
      if (preload || loadParents) {
        loadedFields = loadedFields ?? [];
        if (/*!_loadedFields.contains('tasks.plTask') && */ (preloadFields ==
                null ||
            loadParents ||
            preloadFields.contains('plTask'))) {
          /*_loadedFields.add('tasks.plTask');*/
          obj.plTask = obj.plTask ??
              await obj.getTask(
                  loadParents: loadParents /*, loadedFields: _loadedFields*/);
        }
      } // END RELATIONSHIPS PRELOAD

    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Taskchecklist]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) taskchecklistCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final taskchecklistsFuture = await _obj._mnTaskchecklist.toList(qparams);
    final int count = taskchecklistsFuture[0]['CNT'] as int;
    if (taskchecklistCount != null) {
      taskchecklistCount(count);
    }
    return count;
  }

  /// This method returns List<Taskchecklist> [Taskchecklist]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Taskchecklist>
  Future<List<Taskchecklist>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Taskchecklist> taskchecklistsData =
        await Taskchecklist.fromMapList(data,
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields,
            setDefaultValues: qparams.selectColumns == null);
    return taskchecklistsData;
  }

  /// This method returns Json String [Taskchecklist]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Taskchecklist]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Taskchecklist]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnTaskchecklist.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Taskchecklist]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] =
        'SELECT `id` FROM taskchecklists WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnTaskchecklist.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Taskchecklist]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnTaskchecklist.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Taskchecklist.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnTaskchecklist.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion TaskchecklistFilterBuilder

// region TaskchecklistFields
class TaskchecklistFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fName;
  static TableField get name {
    return _fName = _fName ?? SqlSyntax.setField(_fName, 'name', DbType.text);
  }

  static TableField _fTasksId;
  static TableField get tasksId {
    return _fTasksId =
        _fTasksId ?? SqlSyntax.setField(_fTasksId, 'tasksId', DbType.integer);
  }

  static TableField _fIs_done;
  static TableField get is_done {
    return _fIs_done =
        _fIs_done ?? SqlSyntax.setField(_fIs_done, 'is_done', DbType.bool);
  }
}
// endregion TaskchecklistFields

//region TaskchecklistManager
class TaskchecklistManager extends SqfEntityProvider {
  TaskchecklistManager()
      : super(PotomoDB(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'taskchecklists';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion TaskchecklistManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await PotomoDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await PotomoDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await PotomoDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class PotomoDBSequenceManager extends SqfEntityProvider {
  PotomoDBSequenceManager() : super(PotomoDB());
}
// END OF ENTITIES
